# Generated by Django 5.1.6 on 2025-02-14 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_video', models.FileField(blank=True, null=True, upload_to='static/media/about', verbose_name='Set Background image/video ')),
                ('title', models.CharField(default='Who am I ?', max_length=255)),
                ('des', models.CharField(default='A Web Designer / Python Developer', max_length=300)),
                ('bio', models.TextField(default="I'm a web developer skilled in Html, CSS, Bootstrap, Python, Django, and MySQL, focusing on building scalable and efficient web applications.")),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('github', models.URLField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hero_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(default='Hello, I am', max_length=400, verbose_name='Greet/or Message here')),
                ('name', models.CharField(max_length=100, verbose_name='Your name')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('des', models.TextField(verbose_name='Write short description')),
                ('button_text', models.CharField(default='Expore', max_length=100, verbose_name='Modify button name')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='static/media/', verbose_name='Set Background Image')),
                ('background_video', models.FileField(blank=True, null=True, upload_to='static/media/', verbose_name='Set Background Video')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categories', to='portfolio.about')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=300)),
                ('icon', models.CharField(help_text="Enter a FontAwesome or Bootstrap icon class (e.g., 'fa-solid fa-code')", max_length=100)),
                ('About', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abouts', to='portfolio.about')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='portfolio.category')),
            ],
        ),
        migrations.CreateModel(
            name='SocailLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'Linkedin'), ('github', 'Github'), ('facebook', 'Facebook'), ('x', 'X'), ('whatsapp', 'WhatsApp'), ('mail', 'Mail')], max_length=100)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='FontAwesome class (e.g., fa-brands fa-instagram)', max_length=100)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='portfolio.hero_page')),
            ],
        ),
    ]
