# Generated by Django 5.1.6 on 2025-02-18 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.FileField(blank=True, null=True, upload_to='about_background_image_video/', verbose_name='Set Background image/video')),
                ('title', models.CharField(default='Who am I ?', max_length=255)),
                ('des', models.CharField(default='A Web Designer / Python Developer', max_length=300)),
                ('bio', models.TextField(default="I'm a web developer skilled in Html, CSS, Bootstrap, Python, Django, and MySQL, focusing on building scalable and efficient web applications.")),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('github', models.URLField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('addres', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('background', models.ImageField(blank=True, null=True, upload_to='contact_background')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hero_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_background_image/')),
                ('video', models.FileField(blank=True, null=True, upload_to='home_background_video/')),
                ('mes', models.CharField(default='Hello, I am', max_length=400, verbose_name='Greet/or Message here')),
                ('name', models.CharField(max_length=100, verbose_name='Your name')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('des', models.TextField(verbose_name='Write short description')),
                ('button_text', models.CharField(default='Expore', max_length=100, verbose_name='Modify button name')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the project title.', max_length=255)),
                ('tech', models.CharField(help_text='List the technologies used, such as programming languages, frameworks, and tools.', max_length=300, verbose_name='Technology Stack')),
                ('des', models.TextField(help_text='Provide a brief description of your project, highlighting its features and purpose.')),
                ('live_link', models.URLField(blank=True, help_text="If your project is deployed, enter its live URL. Leave blank if it's not hosted.", null=True)),
                ('source_code', models.URLField(help_text='Enter the GitHub repository link or any source code URL.')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='project_background_image/', verbose_name='Project Section Background Image')),
                ('background_video', models.FileField(blank=True, null=True, upload_to='project_background_video/', verbose_name='Project Section Background Video')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_video', models.FileField(blank=True, null=True, upload_to='resume_background_video/', verbose_name='Set Background Video')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='resume_background_image/', verbose_name='Set Background Image')),
                ('main_title', models.CharField(default='My Resume', max_length=255)),
                ('main_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categories', to='portfolio.about')),
            ],
        ),
        migrations.CreateModel(
            name='ResSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('proficiency', models.IntegerField(help_text='Enter a value between 0 and 100')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('proficiency', models.IntegerField(help_text='Enter a value between 0 and 100')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='portfolio.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('des', models.TextField(max_length=255)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experties', to='portfolio.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('start_year', models.CharField(max_length=20)),
                ('end_year', models.CharField(blank=True, max_length=24, null=True)),
                ('marks', models.CharField(blank=True, max_length=10, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='portfolio.resume')),
            ],
        ),
        migrations.CreateModel(
            name='CustomCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_cards', to='portfolio.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='portfolio.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=300)),
                ('icon', models.CharField(help_text="Enter a FontAwesome or Bootstrap icon class (e.g., 'fa-solid fa-code')", max_length=100)),
                ('About', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abouts', to='portfolio.about')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='portfolio.category')),
            ],
        ),
        migrations.CreateModel(
            name='SocailLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'Linkedin'), ('github', 'Github'), ('facebook', 'Facebook'), ('x', 'X'), ('whatsapp', 'WhatsApp'), ('mail', 'Mail')], max_length=100)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='FontAwesome class (e.g., fa-brands fa-instagram)', max_length=100)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='portfolio.hero_page')),
            ],
        ),
    ]
