# Generated by Django 5.1.6 on 2025-02-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_resumesection_resumecard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumecard',
            name='title',
        ),
    ]
