# Generated by Django 5.1.6 on 2025-02-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_contactinfo_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='addres',
            field=models.CharField(max_length=254),
        ),
    ]
