# Generated by Django 5.1.6 on 2025-02-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_hero_page_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='background',
            field=models.FileField(blank=True, null=True, upload_to='about_background_image_video/', verbose_name='Set Background image/video'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='contact_background'),
        ),
        migrations.AlterField(
            model_name='hero_page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home_background_image/'),
        ),
        migrations.AlterField(
            model_name='hero_page',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='home_background_video/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_background_image/', verbose_name='Project Section Background Image'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='background_video',
            field=models.FileField(blank=True, null=True, upload_to='project_background_video/', verbose_name='Project Section Background Video'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='resume_background_image/', verbose_name='Set Background Image'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='background_video',
            field=models.FileField(blank=True, null=True, upload_to='resume_background_video/', verbose_name='Set Background Video'),
        ),
    ]
